version: '3'
services:
  hozebot:
    build: .
    environment:
      DC_TOKEN: ODk2ODIzOTcyMDE0OTgxMTgx.G_z27n.x4Duz_XTtTnysdVoHO03t_5ZlwfUfQU9Gn10Ok
    volumes:
      - ./hozedata:/root/hozedata


volumes:
  hozedata: