version: '3'
services:
  hozebot:
    build: .
    environment:
      DC_TOKEN: "${DC_TOKEN}"
      GIPHY: "${GIPHY}"
    volumes:
      - ./hozedata:/root/hozedata
      - "/etc/localtime:/etc/localtime:ro"


volumes:
  hozedata: