name: hozebot2
description: A sample command-line application.
version: 1.1.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cron: ^0.5.1
  dio: ^5.0.3
  hive: ^2.2.3
  logging: ^1.1.1
  nyxx: ^5.0.1
  nyxx_interactions: ^4.6.0
  tuple: ^2.0.1
  xrandom: ^0.7.2



dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.0
